#!/bin/bash 
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080 
echo "start" action hook initializing!!

rm -rf ${OPENSHIFT_REPO_DIR}deployments/logs
mkdir ${OPENSHIFT_REPO_DIR}deployments/logs
cd ${OPENSHIFT_REPO_DIR}deployments
nohup ${OPENSHIFT_DATA_DIR}jdk1.8/bin/java -jar Pagani-History.jar -Xms1000m -Xmx1000m --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} 2>&1 &
