#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export OPENSHIFT_DIY_LOG_DIR=$OPENSHIFT_DATA_DIR/logs
rm -f ${OPENSHIFT_DIY_LOG_DIR}bootjava8.log

nohup ${OPENSHIFT_DATA_DIR}jdk1.8/bin/java -jar ${OPENSHIFT_REPO_DIR}deployments/ROOT.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &