#!/bin/bash
export OPENSHIFT_DIY_LOG_DIR=$OPENSHIFT_DATA_DIR/logs

$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn -f $OPENSHIFT_REPO_DIR/pom.xml clean package -s $OPENSHIFT_REPO_DIR/.openshift/action_hooks/settings.xml

nohup java -jar $OPENSHIFT_REPO_DIRdeployments/ROOT.jar > ${OPENSHIFT_DIY_LOG_DIR}bootjava8.log 2>&1 &
